// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqEHZW05yDjvpovTu69Z0eHG75Rw3K3E4',
    appId: '1:317173284656:web:db52d1bb9ab5b2c32252f5',
    messagingSenderId: '317173284656',
    projectId: 'starbucks-analiz',
    authDomain: 'starbucks-analiz.firebaseapp.com',
    storageBucket: 'starbucks-analiz.firebasestorage.app',
    measurementId: 'G-6C3KHF3TQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhqse32xgQTtYF4eI1pV7GfgPv-dCUMTY',
    appId: '1:317173284656:android:73e8b95db81a08152252f5',
    messagingSenderId: '317173284656',
    projectId: 'starbucks-analiz',
    storageBucket: 'starbucks-analiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAKj7NGjbMN1MHK-lrAUmSeuRO5qhRKOI',
    appId: '1:317173284656:ios:39b3bd8c3475cdcc2252f5',
    messagingSenderId: '317173284656',
    projectId: 'starbucks-analiz',
    storageBucket: 'starbucks-analiz.firebasestorage.app',
    iosBundleId: 'com.example.akilliKahveUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAKj7NGjbMN1MHK-lrAUmSeuRO5qhRKOI',
    appId: '1:317173284656:ios:39b3bd8c3475cdcc2252f5',
    messagingSenderId: '317173284656',
    projectId: 'starbucks-analiz',
    storageBucket: 'starbucks-analiz.firebasestorage.app',
    iosBundleId: 'com.example.akilliKahveUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqEHZW05yDjvpovTu69Z0eHG75Rw3K3E4',
    appId: '1:317173284656:web:38a93661681b3b942252f5',
    messagingSenderId: '317173284656',
    projectId: 'starbucks-analiz',
    authDomain: 'starbucks-analiz.firebaseapp.com',
    storageBucket: 'starbucks-analiz.firebasestorage.app',
    measurementId: 'G-GSPNEBKQTV',
  );
}
